### PR TITLE
🚨(backend) fix warning SSL

### PR DESCRIPTION
**Pull request by AntoLC**
## Purpose

The logs were showing a warning about the SSL:
-  You have not set a value for the SECURE_HSTS_SECONDS setting.
- Your SECURE_SSL_REDIRECT setting is not set to True.

This commit fixes the warning by setting the SECURE_HSTS_SECONDS to 31536000 and SECURE_SSL_REDIRECT to True.

```
security.W004: You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
security.W008: Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
```

## Demo

image

### CODE REVIEW

**Comment by Morendil** [comment]
Hi @AntoLC I'm not sure what to do about this PR - what's to be done to get from Draft to Ready to review ? I think I understand the changes to `settings.py` from the first commit but I'm not sure what motivated the changes in the later two commits. Does the `SECURE_SSL_REDIRECT` change have an impact on Helm deployments  ?

**Comment by mjeammet** [comment]
Seems fixed to me. WDYT @AntoLC  ?
image

**Comment by Morendil** [comment]
@mjeammet Ah, I understand why now. The warnings were silenced in [staging](https://github.com/numerique-gouv/people/blob/989239082e99f9e07434710c3f76f4af2444a8ff/src/helm/env.d/staging/values.desk.yaml.gotmpl#L39), [preprod](https://github.com/numerique-gouv/people/blob/989239082e99f9e07434710c3f76f4af2444a8ff/src/helm/env.d/preprod/values.desk.yaml.gotmpl#L39) and [prod](https://github.com/numerique-gouv/people/blob/989239082e99f9e07434710c3f76f4af2444a8ff/src/helm/env.d/production/values.desk.yaml.gotmpl#L39) via PR #235 and #236.

**Comment by Morendil** [comment]
Given #432 I think we can safely close this, however the settings chosen in #432 are not adequate for production uses, where a one- or two-year period is considered best practice. On the other hand, in production these values are normally set by the load balancer or proxies, and this is [apparently](https://domsignal.com/test/v28vg7ht05143uc24z1pi3nlx1gvdinu) the case in our current setup.

**Pull request closed without merging**
